"""add audience and cta_href to pricing_plans

Revision ID: c9d0e1f2a3b4
Revises: b8c9d0e1f2a3
Create Date: 2026-07-21 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d0e1f2a3b4'
down_revision: Union[str, Sequence[str], None] = 'b8c9d0e1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('pricing_plans', sa.Column('audience', sa.String(length=20), nullable=False, server_default='main'))
    op.add_column('pricing_plans', sa.Column('cta_href', sa.String(length=255), nullable=True))
    op.alter_column('pricing_plans', 'audience', server_default=None)

    # `key` was globally unique before — now it's unique per audience
    # instead. Look up the existing constraint's name rather than assuming
    # it, since it was auto-generated by the original migration.
    conn = op.get_bind()
    conn.execute(sa.text("""
        DO $$
        DECLARE
            existing_name text;
        BEGIN
            SELECT conname INTO existing_name
            FROM pg_constraint
            WHERE conrelid = 'pricing_plans'::regclass AND contype = 'u';
            IF existing_name IS NOT NULL THEN
                EXECUTE 'ALTER TABLE pricing_plans DROP CONSTRAINT ' || quote_ident(existing_name);
            END IF;
        END $$;
    """))
    op.create_unique_constraint('uq_pricing_plan_audience_key', 'pricing_plans', ['audience', 'key'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('uq_pricing_plan_audience_key', 'pricing_plans', type_='unique')
    op.create_unique_constraint('pricing_plans_key_key', 'pricing_plans', ['key'])
    op.drop_column('pricing_plans', 'cta_href')
    op.drop_column('pricing_plans', 'audience')
