"""
SEED CONTENT — load the initial site text into the database.

Run once (and re-run safely) to populate the content table with the English
master strings and their auto-translated versions.

    uv run python -m app.seed_content

Idempotent: existing keys are updated, not duplicated. As we move more pages
into the content system, add their English strings to CONTENT below.
"""

import asyncio

from sqlalchemy import select

from app.config import settings
from app.database import AsyncSessionLocal
from app.models import ContentEntry

# English master strings, keyed the same way the frontend reads them.
# (Batch 1: full home page.)
CONTENT: dict[str, str] = {
    # Hero
    "home.hero.badge": "Trusted by 5,000+ athletes nationwide",
    "home.hero.titleTop": "We Measure Your",
    "home.hero.titleBottom": "Athletic Mindset",
    "home.hero.subtitle": (
        "The only psychologist-engineered assessment that measures 22 dimensions "
        "of your mental game in 15 minutes. So you can train it."
    ),
    "home.hero.cta": "Take Free Assessment",
    "home.hero.note": "No credit card required · 15 min · Instant results",
    "home.hero.pllPartner": "Official PLL Academy Partner",
    "home.hero.trust1": "Engineered by Psychologists",
    "home.hero.trust2": "Science-Backed",
    "home.hero.trust3": "Used by Universities & Clubs",
    "home.hero.scroll": "Scroll to explore",
    # Stats
    "home.stats.titleA": "The Most Comprehensive Mental",
    "home.stats.titleB": "Performance Assessment",
    "home.stats.subtitle": (
        "Our four-level scoring architecture gives athletes the deepest "
        "understanding of their mental game available anywhere."
    ),
    "home.stats.phases.label": "Phases",
    "home.stats.phases.desc": "Preparation · Competition · Teamwork",
    "home.stats.factors.label": "Factors",
    "home.stats.factors.desc": "Core mental performance drivers",
    "home.stats.dimensions.label": "Dimensions",
    "home.stats.dimensions.desc": "Granular mental skill measures",
    "home.stats.situational.label": "Situational Mindsets",
    "home.stats.situational.desc": "Context-specific mental states",
    # Report preview
    "home.report.eyebrow": "Your Report",
    "home.report.titleA": "See What You'll",
    "home.report.titleB": "Discover",
    "home.report.subtitle": (
        "A snapshot of your personalized mental performance profile. Scored "
        "across 8 factors and 22 dimensions using T-scores."
    ),
    "home.report.scores.mentalToughness": "Mental Toughness",
    "home.report.scores.focus": "Focus",
    "home.report.scores.drive": "Drive",
    "home.report.scores.coachability": "Coachability",
    "home.report.scores.grit": "Grit",
    "home.report.scores.leadership": "Leadership",
    "home.report.scores.workStyle": "Work Style",
    "home.report.scores.teamOrientation": "Team Orientation",
    "home.report.bands.high": "High",
    "home.report.bands.average": "Average",
    "home.report.bands.veryHigh": "Very High",
    "home.report.bands.aboveAverage": "Above Average",
    "home.report.bands.belowAverage": "Below Average",
    "home.report.totalScore": "Total AM Score",
    "home.report.sampleLabel": "Sample Athlete Report",
    "home.report.profileTitle": "Athletic Mindset Profile",
    "home.report.gameplanLabel": "Personalized Gameplan:",
    "home.report.gameplanLine1": (
        "Based on your scores, here are the mental skills routines recommended "
        "for your development..."
    ),
    "home.report.gameplanLine2": (
        "Your primary focus areas are Visualization and Self-Talk techniques "
        "applied to competition pressure scenarios..."
    ),
    "home.report.unlock": "Take the assessment to unlock your full Gameplan",
    "home.report.getReport": "Get My Report",
    # What we measure
    "home.measure.eyebrow": "What We Measure",
    "home.measure.titleA": "Three Phases of",
    "home.measure.titleB": "Mental Performance",
    "home.measure.subtitle": (
        "Every athlete is scored across preparation, competition, and teamwork, "
        "giving a complete picture of mental readiness from training to game day."
    ),
    "home.measure.phases.preparation.name": "Preparation",
    "home.measure.phases.preparation.desc": "How athletes prepare, train, and receive coaching",
    "home.measure.phases.competition.name": "Competition",
    "home.measure.phases.competition.desc": "How athletes perform and compete under pressure",
    "home.measure.phases.teamwork.name": "Teamwork",
    "home.measure.phases.teamwork.desc": "Team contribution, leadership, and situational response",
    "home.measure.factors.workStyle.name": "Work Style",
    "home.measure.factors.workStyle.desc": "Approach to training and practice habits",
    "home.measure.factors.coachability.name": "Coachability",
    "home.measure.factors.coachability.desc": "Receptiveness to feedback and instruction",
    "home.measure.factors.grit.name": "Grit",
    "home.measure.factors.grit.desc": "Perseverance and passion for long-term goals",
    "home.measure.factors.drive.name": "Drive",
    "home.measure.factors.drive.desc": "Internal motivation and competitive desire",
    "home.measure.factors.focus.name": "Focus",
    "home.measure.factors.focus.desc": "Concentration and attention management",
    "home.measure.factors.mentalToughness.name": "Mental Toughness",
    "home.measure.factors.mentalToughness.desc": "Resilience under pressure and adversity",
    "home.measure.factors.leadership.name": "Leadership Potential",
    "home.measure.factors.leadership.desc": "Ability to inspire and guide teammates",
    "home.measure.factors.teamOrientation.name": "Team Orientation",
    "home.measure.factors.teamOrientation.desc": "Collaboration and team-first mentality",
    "home.measure.noteA": "Each factor breaks down into multiple dimensions, totaling",
    "home.measure.noteHighlight": "22 granular measures",
    "home.measure.noteB": "of your mental game.",
    # How it works
    "home.how.eyebrow": "How It Works",
    "home.how.titleA": "From Assessment to",
    "home.how.titleB": "Action",
    "home.how.subtitle": (
        "A clear path from understanding your mental game to actively improving "
        "it, backed by science, guided by experts."
    ),
    "home.how.steps.assess.title": "Take the Assessment",
    "home.how.steps.assess.desc": (
        "Complete our psychologist-designed assessment covering all 22 dimensions "
        "of mental performance. Takes about 15 minutes."
    ),
    "home.how.steps.scores.title": "Get Your Scores",
    "home.how.steps.scores.desc": (
        "Receive your T-scores across all 8 factors, benchmarked against thousands "
        "of athletes. See exactly where you stand."
    ),
    "home.how.steps.gameplan.title": "Read Your Gameplan",
    "home.how.steps.gameplan.desc": (
        "Get a personalized report with actionable steps, written differently for "
        "athletes, parents, and coaches."
    ),
    "home.how.steps.train.title": "Train & Improve",
    "home.how.steps.train.desc": (
        "Follow your mental skills routines, track progress over time, and reassess "
        "to see your growth."
    ),
    # Solutions
    "home.solutions.eyebrow": "Built For Everyone",
    "home.solutions.titleA": "Solutions For Your",
    "home.solutions.titleB": "Entire Team",
    "home.solutions.subtitle": (
        "Same assessment data, different experiences, tailored for each person in "
        "the athlete's support system."
    ),
    "home.solutions.totalScore": "Total AM Score",
    "home.solutions.aboveAverage": "Above Average",
    "home.solutions.getStarted": "Get Started Free",
    "home.solutions.athlete.short": "Athletes",
    "home.solutions.athlete.tagline": "Know your mental game. Own your mental game.",
    "home.solutions.athlete.description": (
        "Get a complete mental performance profile scored across 22 dimensions. "
        "Understand exactly where your strengths are and where to focus your mental "
        "training for the biggest gains."
    ),
    "home.solutions.athlete.features.0": "Personal T-score across all 22 dimensions",
    "home.solutions.athlete.features.1": "Benchmarked against thousands of athletes in your sport",
    "home.solutions.athlete.features.2": "Personalized Gameplan with actionable mental skills",
    "home.solutions.athlete.features.3": "Progress tracking with reassessment over time",
    "home.solutions.athlete.features.4": "Mental training routines tailored to your weak spots",
    "home.solutions.parent.short": "Parents",
    "home.solutions.parent.tagline": "Finally understand what's happening inside your athlete's head.",
    "home.solutions.parent.description": (
        "Get a jargon-free report that helps you support your child's mental "
        "development, without undermining their coach or adding pressure."
    ),
    "home.solutions.parent.features.0": "Simple, clear language, no psychology degree needed",
    "home.solutions.parent.features.1": "Understand your child's mental strengths and growth areas",
    "home.solutions.parent.features.2": "Communication tips to support without adding pressure",
    "home.solutions.parent.features.3": "Progress visibility over time",
    "home.solutions.parent.features.4": "Coaching tips so you know how to help at home",
    "home.solutions.coach.short": "Coaches",
    "home.solutions.coach.tagline": "Coach the whole athlete. Not just the physical.",
    "home.solutions.coach.description": (
        "See your entire roster's mental readiness at a glance. Know which athletes "
        "need attention, who's ready to lead, and how to communicate with each "
        "player based on their profile."
    ),
    "home.solutions.coach.features.0": "Roster-wide mental readiness dashboard",
    "home.solutions.coach.features.1": "Individual athlete reports with coaching language",
    "home.solutions.coach.features.2": "Identify at-risk athletes before performance drops",
    "home.solutions.coach.features.3": "Leadership potential and role recommendations",
    "home.solutions.coach.features.4": "Revenue share, earn from every athlete you bring in",
    "home.solutions.organization.short": "Clubs",
    "home.solutions.organization.tagline": "Scale mental performance across your entire program.",
    "home.solutions.organization.description": (
        "Bulk onboard hundreds or thousands of athletes. Get organization-wide "
        "insights, benchmarking, and a branded experience that elevates your program."
    ),
    "home.solutions.organization.features.0": "Bulk athlete import, CSV, links, or QR codes",
    "home.solutions.organization.features.1": "Organization-wide analytics and benchmarks",
    "home.solutions.organization.features.2": "Dedicated account support",
    "home.solutions.organization.features.3": "Volume pricing with club-level billing",
    "home.pricing.eyebrow": "Pricing",
    "home.pricing.titleA": "Choose Your",
    "home.pricing.titleB": "Level",
    "home.pricing.subtitle": "Start free. Upgrade when you're ready to unlock the full depth of your mental performance profile.",
    "home.pricing.monthly": "Monthly",
    "home.pricing.yearly": "Yearly",
    "home.pricing.toggleAria": "Toggle billing period",
    "home.pricing.save": "Save 15%",
    "home.pricing.mostPopular": "Most Popular",
    "home.pricing.perYear": "/year",
    "home.pricing.billedYearly": "Billed as $125/year",
    "home.pricing.unlockWith": "Unlock with Elite",
    "home.pricing.note": "All plans include our psychologist-engineered 22-dimension assessment. No credit card required for free tier.",
    "home.pricing.tiers.free.name": "Free",
    "home.pricing.tiers.free.description": "Take the full assessment. See 1 of 8 factors unlocked.",
    "home.pricing.tiers.free.features.0": "Full 22-dimension assessment",
    "home.pricing.tiers.free.features.1": "1 factor score unlocked (of 8)",
    "home.pricing.tiers.free.features.2": "Overall Athletic Mindset score",
    "home.pricing.tiers.free.features.3": "Basic percentile ranking",
    "home.pricing.tiers.free.features.4": "One assessment per year",
    "home.pricing.tiers.free.locked.0": "Full 8-factor breakdown",
    "home.pricing.tiers.free.locked.1": "22-dimension detailed scores",
    "home.pricing.tiers.free.locked.2": "Personalized Gameplan",
    "home.pricing.tiers.free.locked.3": "Mental skills routines",
    "home.pricing.tiers.free.locked.4": "Sport-specific benchmarking",
    "home.pricing.tiers.free.cta": "Start Free Assessment",
    "home.pricing.tiers.elite.name": "Elite",
    "home.pricing.tiers.elite.description": "Unlock your complete mental performance profile.",
    "home.pricing.tiers.elite.features.0": "Everything in Free, plus:",
    "home.pricing.tiers.elite.features.1": "Full detailed report — all 22 dimensions",
    "home.pricing.tiers.elite.features.2": "Personalized Gameplan with mental skills",
    "home.pricing.tiers.elite.features.3": "Sport-specific benchmarking",
    "home.pricing.tiers.elite.features.4": "Elite athlete comparison",
    "home.pricing.tiers.elite.features.5": "Unlimited reassessments",
    "home.pricing.tiers.elite.features.6": "Parent & Coach report versions",
    "home.pricing.tiers.elite.features.7": "Progress tracking over time",
    "home.pricing.tiers.elite.features.8": "Priority support",
    "home.pricing.tiers.elite.cta": "Get Elite Access",
    "home.pricing.tiers.team.name": "Team",
    "home.pricing.tiers.team.description": "Scale across your entire organization.",
    "home.pricing.tiers.team.features.0": "Everything in Elite, plus:",
    "home.pricing.tiers.team.features.1": "Bulk athlete onboarding (CSV, links, QR)",
    "home.pricing.tiers.team.features.2": "Coach dashboard with roster view",
    "home.pricing.tiers.team.features.3": "Team-level mental readiness analytics",
    "home.pricing.tiers.team.features.4": "At-risk athlete identification",
    "home.pricing.tiers.team.features.5": "Team Mindset Assessment included",
    "home.pricing.tiers.team.features.6": "Partner revenue share program",
    "home.pricing.tiers.team.features.7": "Dedicated account support",
    "home.pricing.tiers.team.cta": "Contact Sales",
    # Testimonials
    "home.testimonials.eyebrow": "Testimonials",
    "home.testimonials.titleA": "Real Athletes.",
    "home.testimonials.titleB": "Real Results.",
    "home.testimonials.featured.quote": (
        "On Saturday I took my girls field hockey team to a 1v1 shootout and one of "
        "the players said 'My assessment said I have a hard time under pressure and "
        "this is what I have to do', she was referring to one of the Athletic "
        "Mindset relaxation techniques, and then went out and scored a huge goal for "
        "us. From that moment on the rest of my girls bought into the program. I went "
        "on to be coach of the year, and now all juniors and seniors at Friends "
        "Academy utilize this amazing platform."
    ),
    "home.testimonials.featured.role": "Head Field Hockey Coach",
    "home.testimonials.items.0.quote": (
        "I feel that the assessment is essential in self-reflection, something every "
        "athlete should have to take. It puts your strengths and weaknesses at the "
        "forefront of the mind. It brings feelings into life, into reality."
    ),
    "home.testimonials.items.0.role": "Athlete",
    "home.testimonials.items.1.quote": (
        "This really was very accurate about me. This test helped me show what else "
        "I'm good at but also what I can improve on. I feel like the stuff that it "
        "told me to do will make me a better player."
    ),
    "home.testimonials.items.1.role": "Soccer Player",
    "home.testimonials.items.2.quote": (
        "To be frank, this assessment exposed the horrifying truth on some of my "
        "weaknesses and strengths. I was asked questions that stimulated my mind and "
        "allowed me to look at things from a different aspect."
    ),
    "home.testimonials.items.2.role": "Athlete",
    "home.testimonials.items.3.quote": (
        "The feedback highlights my strengths and weaknesses both extrinsically and "
        "intrinsically. It provides a detailed account of how my personal qualities "
        "measure up to the standards of a typical athlete."
    ),
    "home.testimonials.items.3.role": "Athlete",
    "home.testimonials.items.4.quote": (
        "All of our girls completed their individual assessment. I have LOVED seeing "
        "the individual results! The summary is awesome, very helpful!"
    ),
    "home.testimonials.items.4.role": "Women's Lacrosse Coach",
    # Final CTA
    "home.cta.titleA": "Ready to Discover Your",
    "home.cta.titleB": "Athletic Mindset?",
    "home.cta.subtitle": (
        "Take the free assessment and get your mental performance profile in 15 "
        "minutes. No credit card required."
    ),
    "home.cta.primary": "Take Free Assessment",
    "home.cta.secondary": "Request a Demo",
    "home.cta.stat1": "Free to start",
    "home.cta.stat2": "15 min assessment",
    "home.cta.stat3": "Instant results",
    "home.cta.stat4": "60+ sports supported",
    # --- Athletes page ---
    # Hero
    "athletes.hero.pre": "Don't just know your mental game.",
    "athletes.hero.titleA": "Own It.",
    "athletes.hero.titleB": "So It Doesn't Own You.",
    "athletes.hero.subtitle": (
        "Get your complete mental performance profile, scored across 22 "
        "dimensions, benchmarked against athletes in your sport."
    ),
    "athletes.hero.cta": "Get Your Report",
    "athletes.hero.note": "15-minute assessment · Instant results · Personalized gameplan",
    "athletes.hero.statDimensions": "Dimensions",
    "athletes.hero.statFactors": "Factors",
    "athletes.hero.statPhases": "Phases",
    "athletes.hero.statMinutes": "Minutes",
    # What you get
    "athletes.get.eyebrow": "What You Get",
    "athletes.get.titleA": "Your Complete Mental",
    "athletes.get.titleB": "Performance Profile",
    "athletes.get.subtitle": (
        "One assessment. 15 minutes. A deep, scientific look at the mental side "
        "of your game that no physical test can measure."
    ),
    "athletes.get.features.tscores.title": "T-Scores Across 22 Dimensions",
    "athletes.get.features.tscores.desc": "Every aspect of your mental game scored on a scientific scale, from Focus to Grit to Mental Toughness.",
    "athletes.get.features.gameplan.title": "Personalized Gameplan",
    "athletes.get.features.gameplan.desc": "Actionable development strategies tailored to your weakest areas with specific mental skills routines.",
    "athletes.get.features.situational.title": "Situational Mindset Analysis",
    "athletes.get.features.situational.desc": "7 mindset profiles showing how you perform under pressure, deal with setbacks, and lead your team.",
    "athletes.get.features.benchmark.title": "Sport-Specific Benchmarking",
    "athletes.get.features.benchmark.desc": "See how you stack up against thousands of athletes in your sport, age group, and competition level.",
    "athletes.get.features.elite.title": "Elite Comparison",
    "athletes.get.features.elite.desc": "Compare your scores directly against D1 and professional athletes to see where you stand.",
    "athletes.get.features.routines.title": "Mental Skills Routines",
    "athletes.get.features.routines.desc": "Self-talk, visualization, emotional control, and goal-setting techniques assigned to your specific gaps.",
    # Framework
    "athletes.framework.eyebrow": "The Framework",
    "athletes.framework.titleA": "3 Phases. 8 Factors.",
    "athletes.framework.titleB": "22 Dimensions.",
    "athletes.framework.subtitle": "Every dimension of your mental game mapped, measured, and connected to specific development strategies.",
    "athletes.framework.factorsMeasured": "factors measured",
    "athletes.framework.phases.0.name": "Preparation",
    "athletes.framework.phases.0.tagline": "Building the Foundation",
    "athletes.framework.phases.0.factors.0.name": "Grit",
    "athletes.framework.phases.0.factors.0.desc": "Perseverance and motivation for long-term goals",
    "athletes.framework.phases.0.factors.0.dimensions.0": "Intrinsic Motivation",
    "athletes.framework.phases.0.factors.0.dimensions.1": "Persistence",
    "athletes.framework.phases.0.factors.1.name": "Work Style",
    "athletes.framework.phases.0.factors.1.desc": "Attitude and mindset during practice and preparation",
    "athletes.framework.phases.0.factors.1.dimensions.0": "Mastery Approach",
    "athletes.framework.phases.0.factors.1.dimensions.1": "Growth Mindset",
    "athletes.framework.phases.0.factors.2.name": "Coachability",
    "athletes.framework.phases.0.factors.2.desc": "Receptiveness to learning and feedback",
    "athletes.framework.phases.0.factors.2.dimensions.0": "Cooperation",
    "athletes.framework.phases.0.factors.2.dimensions.1": "Feedback Acceptance",
    "athletes.framework.phases.0.factors.2.dimensions.2": "Modesty",
    "athletes.framework.phases.1.name": "Competition",
    "athletes.framework.phases.1.tagline": "Executing Under Pressure",
    "athletes.framework.phases.1.factors.0.name": "Drive",
    "athletes.framework.phases.1.factors.0.desc": "Short-term motivation to compete and win",
    "athletes.framework.phases.1.factors.0.dimensions.0": "Competitiveness",
    "athletes.framework.phases.1.factors.0.dimensions.1": "Challenge Approach",
    "athletes.framework.phases.1.factors.1.name": "Focus",
    "athletes.framework.phases.1.factors.1.desc": "Maintaining positive concentration during events",
    "athletes.framework.phases.1.factors.1.dimensions.0": "Concentration",
    "athletes.framework.phases.1.factors.1.dimensions.1": "Presence",
    "athletes.framework.phases.1.factors.1.dimensions.2": "Visualization Ability",
    "athletes.framework.phases.1.factors.2.name": "Mental Toughness",
    "athletes.framework.phases.1.factors.2.desc": "Confidence, emotional control, and bouncing back",
    "athletes.framework.phases.1.factors.2.dimensions.0": "Positive Coping Style",
    "athletes.framework.phases.1.factors.2.dimensions.1": "Stress Management",
    "athletes.framework.phases.1.factors.2.dimensions.2": "Confidence",
    "athletes.framework.phases.2.name": "Teamwork",
    "athletes.framework.phases.2.tagline": "Excelling as Part of the Unit",
    "athletes.framework.phases.2.factors.0.name": "Leadership Potential",
    "athletes.framework.phases.2.factors.0.desc": "Ability to elevate others and earn trust",
    "athletes.framework.phases.2.factors.0.dimensions.0": "Integrity",
    "athletes.framework.phases.2.factors.0.dimensions.1": "Assertiveness",
    "athletes.framework.phases.2.factors.1.name": "Team Orientation",
    "athletes.framework.phases.2.factors.1.desc": "Contributing to team success and supporting others",
    "athletes.framework.phases.2.factors.1.dimensions.0": "Team Preference",
    "athletes.framework.phases.2.factors.1.dimensions.1": "Reliance",
    "athletes.framework.phases.2.factors.1.dimensions.2": "Team Goal Focus",
    "athletes.framework.phases.2.factors.1.dimensions.3": "Sociability",
    # Report preview
    "athletes.report.eyebrow": "Report Preview",
    "athletes.report.titleA": "See What Your Report",
    "athletes.report.titleB": "Looks Like",
    "athletes.report.subtitle": "A real snapshot from the Athletic Mindset Athlete Report. Your actual results will be based on your unique assessment responses.",
    "athletes.report.scores.mentalToughness": "Mental Toughness",
    "athletes.report.scores.focus": "Focus",
    "athletes.report.scores.drive": "Drive",
    "athletes.report.scores.coachability": "Coachability",
    "athletes.report.scores.grit": "Grit",
    "athletes.report.scores.leadership": "Leadership",
    "athletes.report.scores.workStyle": "Work Style",
    "athletes.report.scores.teamOrientation": "Team Orientation",
    "athletes.report.bands.high": "High",
    "athletes.report.bands.average": "Average",
    "athletes.report.bands.veryHigh": "Very High",
    "athletes.report.bands.aboveAverage": "Above Average",
    "athletes.report.bands.belowAvg": "Below Avg",
    "athletes.report.totalScore": "Total AM Score",
    "athletes.report.sampleLabel": "Sample Athlete Report",
    "athletes.report.profileTitle": "Athletic Mindset Profile",
    "athletes.report.gameplanLabel": "Your Personalized Gameplan:",
    "athletes.report.gameplanLine1": "Based on your Work Style and Grit scores, your primary mental skills focus should be on Visualization and Goal-Setting routines...",
    "athletes.report.gameplanLine2": "Recommended routine: 5-minute pre-practice visualization focusing on mastery cues. Add daily journaling...",
    "athletes.report.unlock": "Your full Gameplan unlocks with your report",
    "athletes.report.getReport": "Get My Report",
    # How it helps
    "athletes.help.eyebrow": "How It Helps",
    "athletes.help.titleA": "Your Report Helps You",
    "athletes.help.titleB": "Level Up",
    "athletes.help.benefits.0": "Identify areas of your mental approach that require improvement and use suggested strategies to fix them",
    "athletes.help.benefits.1": "Understand the situations in competition that will be most challenging and how to maximize performance",
    "athletes.help.benefits.2": "Learn how to be more effective and efficient with preparation time",
    "athletes.help.benefits.3": "Communicate to scouts and coaches your mental strengths and development plan",
    "athletes.help.benefits.4": "Track progress over time with reassessments to see real growth",
    "athletes.help.benefits.5": "Get specific mental skills routines, Self-talk, Visualization, Emotional Control, Goal Setting",
    # Testimonials
    "athletes.testimonials.eyebrow": "From Real Athletes",
    "athletes.testimonials.titleA": "Athletes Like You",
    "athletes.testimonials.titleB": "Agree",
    "athletes.testimonials.items.0.quote": "This really was very accurate about me. Since I play soccer I've been told by other coaches what my flaws are and one major flaw is that I need to stay calm on the field and concentrate. This test helped me show what else I'm good at but also what I can improve on. I feel like the stuff that it told me to do will make me a better player.",
    "athletes.testimonials.items.0.sport": "Soccer",
    "athletes.testimonials.items.1.quote": "I feel that the assessment is essential in self-reflection, something every athlete should have to take. It puts your strengths and weaknesses at the forefront of the mind. The fact that it puts words to one's behavior and actions is a big deal. It brings feelings into life, into reality.",
    "athletes.testimonials.items.1.sport": "Athlete",
    "athletes.testimonials.items.2.quote": "This assessment exam exposed the truth on some of my weaknesses and strengths. I was asked questions that was stimulating to my mind and allowed me to look at things from a different aspect. The results disclosed characteristics of myself, that I knew I had, but was in denial about.",
    "athletes.testimonials.items.2.sport": "Athlete",
    "athletes.testimonials.items.3.quote": "The feedback I received is informative about highlighting my strengths and weaknesses both extrinsically and intrinsically. It provides a detailed account of how my personal qualities measure up to the standards of a typical athlete, and suggests how I should improve steadily.",
    "athletes.testimonials.items.3.sport": "Athlete",
    # Pricing
    "athletes.pricing.eyebrow": "Pricing",
    "athletes.pricing.titleA": "Invest in Your",
    "athletes.pricing.titleB": "Mental Edge",
    "athletes.pricing.subtitle": "Start free or go all-in with the Elite Report for the full depth of your mental performance profile.",
    "athletes.pricing.monthly": "Monthly",
    "athletes.pricing.yearly": "Yearly",
    "athletes.pricing.save": "Save 15%",
    "athletes.pricing.recommended": "Recommended",
    "athletes.pricing.perYear": "/year",
    "athletes.pricing.billedYearly": "Billed as $125/year",
    "athletes.pricing.unlockWith": "Unlock with Elite",
    "athletes.pricing.note": "Parents purchasing for their athlete: the Elite report includes a separate Parent Gameplan at no extra cost.",
    "athletes.pricing.tiers.free.name": "Free",
    "athletes.pricing.tiers.free.description": "See where you stand, 1 factor unlocked",
    "athletes.pricing.tiers.free.features.0": "Full 22-dimension assessment",
    "athletes.pricing.tiers.free.features.1": "1 factor score unlocked (of 8)",
    "athletes.pricing.tiers.free.features.2": "Overall Athletic Mindset score",
    "athletes.pricing.tiers.free.features.3": "Basic percentile ranking",
    "athletes.pricing.tiers.free.locked.0": "Full 8-factor detailed breakdown",
    "athletes.pricing.tiers.free.locked.1": "Personalized Gameplan",
    "athletes.pricing.tiers.free.locked.2": "Mental skills routines",
    "athletes.pricing.tiers.free.locked.3": "Sport-specific benchmarking",
    "athletes.pricing.tiers.free.cta": "Start Free",
    "athletes.pricing.tiers.elite.name": "Elite Report",
    "athletes.pricing.tiers.elite.description": "The complete mental performance experience",
    "athletes.pricing.tiers.elite.features.0": "Everything in Free, plus:",
    "athletes.pricing.tiers.elite.features.1": "Full detailed report, all 22 dimensions",
    "athletes.pricing.tiers.elite.features.2": "Personalized Gameplan with mental skills",
    "athletes.pricing.tiers.elite.features.3": "Sport-specific benchmarking",
    "athletes.pricing.tiers.elite.features.4": "Elite athlete comparison (D1/Pro)",
    "athletes.pricing.tiers.elite.features.5": "7 Situational Mindset profiles",
    "athletes.pricing.tiers.elite.features.6": "Unlimited reassessments",
    "athletes.pricing.tiers.elite.features.7": "Progress tracking over time",
    "athletes.pricing.tiers.elite.features.8": "Parent & Coach report included",
    "athletes.pricing.tiers.elite.cta": "Get Elite Report",
    # Final CTA
    "athletes.cta.titleA": "Ready to Discover Your",
    "athletes.cta.titleB": "Athletic Mindset?",
    "athletes.cta.subtitle": "15 minutes. 22 dimensions. A personalized gameplan to train your mind like you train your body.",
    "athletes.cta.button": "Get Your Report",
    "athletes.cta.stat1": "Instant results",
    "athletes.cta.stat2": "60+ sports supported",
    "athletes.cta.stat3": "Science-backed",
    # --- Parents page ---
    # Hero
    "parents.hero.pre": "Behind every athlete who overcomes pressure, there's a parent who knew what to say.",
    "parents.hero.titleA": "You Can Be",
    "parents.hero.titleB": "That Parent.",
    "parents.hero.subtitle": (
        "Athletic Mindset gives you the insight, the language, and the gameplan "
        "to support your athlete's mental game — not just their stats."
    ),
    "parents.hero.cta": "Get the Parent Report",
    "parents.hero.note": "No psychology background needed · Clear, jargon-free guidance",
    "parents.hero.scroll": "Understand how your child thinks while they compete.",
    # What you get
    "parents.get.eyebrow": "The Parent Report",
    "parents.get.titleA": "Finally Understand What's",
    "parents.get.titleB": "In Their Head",
    "parents.get.subtitle": (
        "Your athlete takes the assessment. You get a report built just for "
        "parents — focused on how to support them, not on performance metrics."
    ),
    "parents.get.features.0.title": "Zero Jargon",
    "parents.get.features.0.desc": "Clear, simple language written for parents — no psychology degree required. Just an honest picture of your child's mental game.",
    "parents.get.features.1.title": "Know What to Say",
    "parents.get.features.1.desc": "Specific guidance for the conversations that matter — including the toughest one of all: the car ride home after a tough game.",
    "parents.get.features.2.title": "Support, Don't Pressure",
    "parents.get.features.2.desc": "Understand your child's strengths and growth areas so you can encourage without adding pressure or undermining their coach.",
    "parents.get.features.3.title": "Track Their Growth",
    "parents.get.features.3.desc": "Watch your athlete develop over time with reassessments — celebrate real progress in mental skills, not just the scoreboard.",
    "parents.get.features.4.title": "Never Framed as Failure",
    "parents.get.features.4.desc": "Low scores are always presented as opportunities to develop — never as deficiencies. Your child stays motivated and confident.",
    "parents.get.features.5.title": "Stay in the Loop",
    "parents.get.features.5.desc": "Get simplified summaries of your athlete's results and notifications so you're always part of their development journey.",
    # Bridge section
    "parents.bridge.eyebrow": "Bridge the Communication Gap",
    "parents.bridge.titleA": "Know What to Say on the",
    "parents.bridge.titleB": "Car Ride Home",
    "parents.bridge.subtitle": (
        "One of the greatest challenges for sports parents is knowing what to say "
        "after a game. The Parent Report gives you a specific blueprint — so you "
        "can support your athlete's mental game while keeping your relationship strong."
    ),
    "parents.bridge.points.0": "Shift the car-ride-home conversation from critiquing errors to supporting their mental approach",
    "parents.bridge.points.1": "Know whether your child is struggling with arousal control or simply needs a different style of feedback",
    "parents.bridge.points.2": "Offer targeted encouragement using real data — not generic questions",
    "parents.bridge.points.3": "Reduce the friction caused by subjective coaching from the sideline",
    "parents.bridge.points.4": "Speak the same language as the assessment, so your child feels understood rather than judged",
    "parents.bridge.points.5": "Spot early signs of burnout or declining motivation before they lead to quitting",
    # Testimonials
    "parents.testimonials.eyebrow": "What Families Say",
    "parents.testimonials.titleA": "Trusted by Athletes &",
    "parents.testimonials.titleB": "Their Families",
    "parents.testimonials.items.0.quote": "I really enjoyed taking this survey. I thought it was very accurate and useful. It definitely made me take a step back to see what I have been doing and gives me ways I can perform better, focus more, and help more with my mental health.",
    "parents.testimonials.items.0.author": "Adam Hidais",
    "parents.testimonials.items.0.role": "Athlete",
    "parents.testimonials.items.1.quote": "The Athletic Mindset assessment was very accurate. I agree one hundred percent with my results and reading it was crazy to see how accurate it was. I found myself taking pictures of my results and sending them to old teammates and recommending the test to them as well.",
    "parents.testimonials.items.1.author": "Kayla Mieranda",
    "parents.testimonials.items.1.role": "Athlete",
    # Pricing
    "parents.pricing.eyebrow": "Pricing",
    "parents.pricing.titleA": "One Assessment.",
    "parents.pricing.titleB": "Two Reports.",
    "parents.pricing.subtitle": "Your athlete gets their complete profile. You get a dedicated Parent Gameplan — both included in the Elite bundle.",
    "parents.pricing.monthly": "Monthly",
    "parents.pricing.yearly": "Yearly",
    "parents.pricing.save": "Save 3%",
    "parents.pricing.bestValue": "Best Value",
    "parents.pricing.perYear": "/year",
    "parents.pricing.unlockWith": "Unlock with Elite",
    "parents.pricing.note": "Create the account with your athlete's name during checkout. The Parent Gameplan is generated automatically alongside their report.",
    "parents.pricing.tiers.free.name": "Free",
    "parents.pricing.tiers.free.description": "See where your athlete stands — 1 factor unlocked",
    "parents.pricing.tiers.free.features.0": "Full 22-dimension assessment",
    "parents.pricing.tiers.free.features.1": "1 factor score unlocked (of 8)",
    "parents.pricing.tiers.free.features.2": "Overall Athletic Mindset score",
    "parents.pricing.tiers.free.features.3": "Basic percentile ranking",
    "parents.pricing.tiers.free.locked.0": "Full Parent Gameplan report",
    "parents.pricing.tiers.free.locked.1": "Communication & support guidance",
    "parents.pricing.tiers.free.locked.2": "8-factor detailed breakdown",
    "parents.pricing.tiers.free.locked.3": "Progress tracking over time",
    "parents.pricing.tiers.free.cta": "Start Free",
    "parents.pricing.tiers.elite.name": "Athlete + Parent Elite",
    "parents.pricing.tiers.elite.description": "The complete report for your athlete — and for you.",
    "parents.pricing.tiers.elite.features.0": "Everything in Free, plus:",
    "parents.pricing.tiers.elite.features.1": "Full Athlete Report — all 22 dimensions",
    "parents.pricing.tiers.elite.features.2": "Dedicated Parent Gameplan report",
    "parents.pricing.tiers.elite.features.3": "Plain-language communication guidance",
    "parents.pricing.tiers.elite.features.4": "How to support without undermining the coach",
    "parents.pricing.tiers.elite.features.5": "Sport-specific benchmarking",
    "parents.pricing.tiers.elite.features.6": "Unlimited reassessments",
    "parents.pricing.tiers.elite.features.7": "Progress tracking over time",
    "parents.pricing.tiers.elite.cta": "Get Athlete + Parent Elite",
    # CTA
    "parents.cta.titleA": "Be the Parent Who",
    "parents.cta.titleB": "Knows What to Say",
    "parents.cta.subtitle": "Give your athlete the mental edge — and give yourself the language to support them every step of the way.",
    "parents.cta.button": "Get the Parent Report",
    # --- Coaches page ---
    # Hero
    "coaches.hero.pre": "You know who's struggling physically. Do you know who's struggling mentally?",
    "coaches.hero.titleA": "Build a Mentally",
    "coaches.hero.titleB": "Tougher Roster.",
    "coaches.hero.subtitle": (
        "Athletic Mindset gives coaches a complete mental readiness picture for "
        "every athlete, without adding hours to your week."
    ),
    "coaches.hero.cta": "Book a Team Demo",
    "coaches.hero.ctaSecondary": "See How It Works",
    "coaches.hero.scroll": "Coach every athlete to their individual mental strengths and gaps.",
    # What you get
    "coaches.get.eyebrow": "The Coach Toolkit",
    "coaches.get.titleA": "A Blueprint for",
    "coaches.get.titleB": "Every Athlete",
    "coaches.get.subtitle": "Your athletes take one assessment. You get individual coach reports, a team-level picture, and a plan for developing each of them.",
    "coaches.get.features.0.title": "A Report on Every Athlete",
    "coaches.get.features.0.desc": "Get a Coach Report for each athlete — their mental strengths, growth areas, and exactly how to coach them as an individual.",
    "coaches.get.features.1.title": "Team Mindset Report",
    "coaches.get.features.1.desc": "See your roster as a unit: cohesion, collective confidence, leadership, and culture — not just a collection of individuals.",
    "coaches.get.features.2.title": "Spot At-Risk Athletes",
    "coaches.get.features.2.desc": "Identify who's struggling with pressure, confidence, or motivation before it shows up on the scoreboard.",
    "coaches.get.features.3.title": "Tailored Development Plans",
    "coaches.get.features.3.desc": "Turn each athlete's profile into a clear plan — the right habits, mental skills, and feedback style for how they're wired.",
    "coaches.get.features.4.title": "Track Progress Over Time",
    "coaches.get.features.4.desc": "Reassess through the season and watch mental skills develop, so you can adjust your approach with real data.",
    "coaches.get.features.5.title": "Coach Summary at a Glance",
    "coaches.get.features.5.desc": "A quick-read summary across your whole roster — the headline insights you need without hours of reading.",
    # How it works
    "coaches.how.eyebrow": "How It Works",
    "coaches.how.titleA": "Mental Readiness,",
    "coaches.how.titleB": "Without the Extra Hours",
    "coaches.how.subtitle": "No new software to learn and no hours added to your week. Invite your team and let the reports do the heavy lifting.",
    "coaches.how.steps.0.title": "Invite Your Roster",
    "coaches.how.steps.0.desc": "Send one link to your team. Each athlete completes the 15-minute assessment on their own phone.",
    "coaches.how.steps.1.title": "Athletes Get Assessed",
    "coaches.how.steps.1.desc": "The psychologist-engineered assessment scores each athlete across 22 dimensions of their mental game.",
    "coaches.how.steps.2.title": "You Get the Reports",
    "coaches.how.steps.2.desc": "Receive a coach report for every athlete plus a team report — insights, not raw numbers.",
    "coaches.how.steps.3.title": "Coach the Mental Game",
    "coaches.how.steps.3.desc": "Use the plans to develop each athlete and strengthen your team's culture all season long.",
    # Recruitment
    "coaches.recruit.eyebrow": "Recruiting & Psychological Fit",
    "coaches.recruit.titleA": "Recruit the Mindset,",
    "coaches.recruit.titleB": "Not Just the Measurables",
    "coaches.recruit.subtitle": (
        "The right athlete is more than stats and film. Athletic Mindset gives "
        "you the final piece of the scouting puzzle — objective data on the "
        "mental traits that decide who thrives at the next level."
    ),
    "coaches.recruit.points.0": "Look past the highlight reel — evaluate coachability and growth mindset before you offer a spot",
    "coaches.recruit.points.1": "Predict how a recruit will handle the jump to a more demanding level of play",
    "coaches.recruit.points.2": "Identify high-ceiling athletes with the grit to push through development plateaus",
    "coaches.recruit.points.3": "Assess stress management and self-talk before they ever step in your locker room",
    "coaches.recruit.points.4": "Minimize the risk of a bad fit and protect the mental fabric of your roster",
    "coaches.recruit.points.5": "Manage psychological traits as rigorously as physical conditioning",
    # Testimonials
    "coaches.testimonials.eyebrow": "From the Sideline",
    "coaches.testimonials.titleA": "Coaches Are",
    "coaches.testimonials.titleB": "Seeing It Work",
    "coaches.testimonials.items.0.quote": "On Saturday we went to a 1v1 shootout and one of the girls in my lineup said, 'My assessment said I have a hard time under pressure and this is what I need to do.' She referenced her relaxation techniques, went out, and scored a huge goal for us.",
    "coaches.testimonials.items.0.name": "Christine Botti",
    "coaches.testimonials.items.0.role": "Field Hockey Coach · Friends Academy",
    "coaches.testimonials.items.1.quote": "All of our girls completed their individual assessment. I have LOVED seeing the individual results, and the summary is awesome — very helpful.",
    "coaches.testimonials.items.1.name": "Jen O'Brien",
    "coaches.testimonials.items.1.role": "Women's Lacrosse Coach · Virginia Commonwealth University",
    # Pricing
    "coaches.pricing.eyebrow": "Team Pricing",
    "coaches.pricing.titleA": "Equip Your",
    "coaches.pricing.titleB": "Whole Roster",
    "coaches.pricing.subtitle": "Start free with a few athletes, or unlock the full team package with reports for every athlete and your complete Team Mindset picture.",
    "coaches.pricing.mostPopular": "Most Popular",
    "coaches.pricing.unlockWith": "Unlock with Team",
    "coaches.pricing.note": "Running a full club or school?",
    "coaches.pricing.noteLink": "See Club & School",
    "coaches.pricing.noteEnd": "for program-wide pricing.",
    "coaches.pricing.tiers.free.name": "Coach Free",
    "coaches.pricing.tiers.free.description": "Try it with a few of your athletes",
    "coaches.pricing.tiers.free.features.0": "Invite up to 3 athletes",
    "coaches.pricing.tiers.free.features.1": "Coach report for each athlete",
    "coaches.pricing.tiers.free.features.2": "Basic roster view",
    "coaches.pricing.tiers.free.features.3": "One team snapshot",
    "coaches.pricing.tiers.free.locked.0": "Full Team Mindset report",
    "coaches.pricing.tiers.free.locked.1": "Unlimited athletes & teams",
    "coaches.pricing.tiers.free.locked.2": "At-risk athlete alerts",
    "coaches.pricing.tiers.free.locked.3": "Season-long progress tracking",
    "coaches.pricing.tiers.free.cta": "Start Free",
    "coaches.pricing.tiers.team.name": "Team",
    "coaches.pricing.tiers.team.priceNote": "/year · billed annually",
    "coaches.pricing.tiers.team.description": "Everything your roster needs, all season",
    "coaches.pricing.tiers.team.features.0": "Everything in Free, plus:",
    "coaches.pricing.tiers.team.features.1": "Coach report for every athlete",
    "coaches.pricing.tiers.team.features.2": "Full Team Mindset report",
    "coaches.pricing.tiers.team.features.3": "Coach Summary across your roster",
    "coaches.pricing.tiers.team.features.4": "At-risk athlete detection",
    "coaches.pricing.tiers.team.features.5": "Unlimited teams",
    "coaches.pricing.tiers.team.features.6": "Season-long progress tracking",
    "coaches.pricing.tiers.team.features.7": "Priority support",
    "coaches.pricing.tiers.team.cta": "Book a Team Demo",
    # CTA
    "coaches.cta.titleA": "Coach the Whole",
    "coaches.cta.titleB": "Athlete",
    "coaches.cta.subtitle": "Give your program the mental readiness picture that physical training alone can't provide. Book a demo and we'll walk you through it with your team in mind.",
    "coaches.cta.button": "Book a Team Demo",
    # --- Research page ---
    "research.hero.eyebrow": "The Science Behind Athletic Mindset",
    "research.hero.titleA": "Built on",
    "research.hero.titleB": "Real Science",
    "research.hero.subtitle": "Our platform sits at the intersection of sport psychology, organizational psychology, and psychometrics — three disciplines that together create the most comprehensive mental performance assessment available to athletes.",
    "research.disciplines.eyebrow": "Our Foundations",
    "research.disciplines.title": "Three Scientific Disciplines",
    "research.disciplines.subtitle": "Most sport psychology tools use qualitative methods — interviews and observations. We combine that tradition with the quantitative rigor of organizational psychology and psychometrics.",
    "research.disciplines.items.0.title": "Sport Psychology",
    "research.disciplines.items.0.description": "Sport psychology applies social, cognitive, clinical, and physiological psychology to facilitate peak performance, enhance sport participation, and help athletes overcome barriers. Our assessment draws directly from validated sport psychology frameworks measuring motivation, confidence, focus, and composure.",
    "research.disciplines.items.0.links.0": "Association for Applied Sport Psychology (AASP)",
    "research.disciplines.items.0.links.1": "APA — Sports and Performance",
    "research.disciplines.items.1.title": "Organizational Psychology",
    "research.disciplines.items.1.description": "Industrial/organizational psychology is the scientific study of individual, team, and organizational performance using psychological theories and the scientific method. Our platform uses quantitative, data-driven evaluation — examining attitudes, beliefs, and behaviors using statistics to provide objective evaluations rather than subjective observations.",
    "research.disciplines.items.1.links.0": "Society for Industrial-Organizational Psychology (SIOP)",
    "research.disciplines.items.1.links.1": "APA — Industrial-Organizational",
    "research.disciplines.items.2.title": "Psychometrics",
    "research.disciplines.items.2.description": "Psychometrics is the science of measuring psychological attributes reliably and validly. Every dimension in our assessment meets professional reliability standards (α ≥ .70) and is normed against 5,000+ validated athlete assessments. T-scores, percentile rankings, and factor analysis ensure every number has scientific meaning.",
    "research.disciplines.items.2.links.0": "International Test Commission",
    "research.methodology.eyebrow": "Our Methodology",
    "research.methodology.title": "How We Measure the Mental Game",
    "research.methodology.subtitle": "A rigorous, multi-layer scoring system that transforms subjective mental performance into objective, trackable data.",
    "research.methodology.steps.0.title": "Validated Instrument",
    "research.methodology.steps.0.description": "Our assessment is built on peer-reviewed research from sport psychology and organizational psychology, validated against 5,000+ athletes across 60+ sports.",
    "research.methodology.steps.1.title": "Four-Level Architecture",
    "research.methodology.steps.1.description": "22 Dimensions roll up into 8 Factors, which compose 3 Phases (Preparation, Competition, Teamwork), yielding one Total Athletic Mindset Score.",
    "research.methodology.steps.2.title": "T-Score Norming",
    "research.methodology.steps.2.description": "Every score is expressed as a T-score (mean 50, SD 10) against the norming population — giving athletes precise, scientifically anchored feedback on where they stand.",
    "research.methodology.steps.3.title": "Dynamic Benchmarking",
    "research.methodology.steps.3.description": "Athletes receive both a static T-score and a dynamic percentile rank within their sport and competition level, updated with every new assessment in the platform.",
    "research.methodology.steps.4.title": "Role-Specific Reports",
    "research.methodology.steps.4.description": "The same psychometric data generates three different reports — for athletes, parents, and coaches — each written in appropriate language with tailored action items.",
    "research.methodology.steps.5.title": "Evidence-Based Gameplans",
    "research.methodology.steps.5.description": "Every personalized Gameplan recommends from six validated mental skills (Self-Talk, Arousal Control, Visualization, Routines, Goal Setting, Re-Framing) based on the athlete's unique profile.",
    "research.publications.eyebrow": "Published Research",
    "research.publications.title": "Academic Foundations",
    "research.publications.items.0.title": "International Journal of Selection and Assessment",
    "research.publications.items.0.description": "Dr. Marentette's published research on skills assessment methodology and development systems — the scientific approach underlying our 22-dimension scoring engine.",
    "research.publications.items.1.title": "Organizational Psychology Review",
    "research.publications.items.1.description": "Research on team performance, selection, and development — the scientific foundation for our Team Orientation and Leadership Potential factors.",
    "research.publications.items.2.title": "DePaul University — Doctoral Research",
    "research.publications.items.2.description": "Dissertation completed with Dr. Suzanne Bell, an international expert on team performance who leads NASA's CREWS project for astronaut team selection and development.",
    "research.cta.titleA": "Experience the Science",
    "research.cta.titleB": "Yourself",
    "research.cta.subtitle": "Take the free assessment and see how psychometric science translates into a personalized mental performance profile.",
    "research.cta.button": "Take Free Assessment",
    # --- Blog page ---
    "blog.hero.eyebrow": "Reading Room",
    "blog.hero.titleA": "The Mental",
    "blog.hero.titleB": "Performance Lab",
    "blog.hero.subtitle": "Curated research, expert articles, and evidence-based resources on sport psychology, mental toughness, and athlete development — from leading institutions and researchers worldwide.",
    "blog.categories.0": "All",
    "blog.categories.1": "Research",
    "blog.categories.2": "For Parents",
    "blog.categories.3": "For Coaches",
    "blog.categories.4": "Mental Skills",
    "blog.posts.featured.title": "Developing and Training Mental Toughness in Sport: What the Research Shows",
    "blog.posts.featured.excerpt": "A systematic review and meta-analysis of observational studies and experimental interventions examining whether mental toughness can be developed through structured training programs. The findings confirm that psychological skills training produces measurable improvements in mental toughness and performance outcomes across sport contexts.",
    "blog.posts.featured.category": "Research",
    "blog.posts.featured.readTime": "12 min read",
    "blog.posts.featured.date": "BMJ Open Sport & Exercise Medicine",
    "blog.posts.featured.source": "National Institutes of Health (PMC)",
    "blog.posts.featured.publishedIn": "Published in:",
    "blog.posts.featured.readFull": "Read Full Article",
    "blog.grid.empty": "No resources found for this category.",
    "blog.grid.read": "Read",
    "blog.grid.posts.0.title": "Sport-Related Performance Anxiety in Young Athletes: A Clinical Practice Review",
    "blog.grid.posts.0.excerpt": "A comprehensive clinical review examining how performance anxiety manifests in youth athletes, its impact on both performance and well-being, and evidence-based intervention strategies for clinicians and coaches working with young competitors.",
    "blog.grid.posts.0.category": "Research",
    "blog.grid.posts.0.readTime": "15 min read",
    "blog.grid.posts.0.source": "NIH / PMC",
    "blog.grid.posts.1.title": "The Science of Building Athletic Confidence in Youth Athletes",
    "blog.grid.posts.1.excerpt": "An exploration of what research reveals about the 'confidence sweet spot' — the optimal challenge level that builds self-belief without creating anxiety. Draws on Csikszentmihalyi's flow research and Guadagnoli's challenge point framework.",
    "blog.grid.posts.1.category": "For Parents",
    "blog.grid.posts.1.readTime": "8 min read",
    "blog.grid.posts.1.source": "Psychology Today",
    "blog.grid.posts.2.title": "How to Encourage Without Pressuring Your Young Athlete",
    "blog.grid.posts.2.excerpt": "Studies show parental expectations can become a significant source of stress for young athletes. This article examines the line between supportive involvement and harmful pressure, with practical communication frameworks for sports parents.",
    "blog.grid.posts.2.category": "For Parents",
    "blog.grid.posts.2.readTime": "7 min read",
    "blog.grid.posts.2.source": "Dr. Paul McCarthy",
    "blog.grid.posts.3.title": "The Power of Visualization in Sport: What the Research Actually Shows",
    "blog.grid.posts.3.excerpt": "Mental imagery activates the same motor circuits as physical execution — the neural overlap is why visualization accelerates skill acquisition, reduces pre-competition anxiety, and builds confidence that holds up under pressure.",
    "blog.grid.posts.3.category": "Mental Skills",
    "blog.grid.posts.3.readTime": "10 min read",
    "blog.grid.posts.3.source": "Mind Training",
    "blog.grid.posts.4.title": "Grit and Athletic Performance: Perseverance and Passion for Long-Term Goals",
    "blog.grid.posts.4.excerpt": "Angela Duckworth's foundational research demonstrated that achievement entails not only talent but sustained application of effort over time. This piece explores how grit theory applies specifically to athletic development and sport persistence.",
    "blog.grid.posts.4.category": "Research",
    "blog.grid.posts.4.readTime": "6 min read",
    "blog.grid.posts.4.source": "Trine University — Center for Sports Studies",
    "blog.grid.posts.5.title": "Student Athlete Mental Health: Tips for Parents and Coaches",
    "blog.grid.posts.5.excerpt": "Johns Hopkins Medicine outlines how parents and coaches can support student athletes by encouraging balance, fostering healthy coping skills, and helping them navigate the stress and emotional setbacks that come with competitive sport.",
    "blog.grid.posts.5.category": "For Coaches",
    "blog.grid.posts.5.readTime": "6 min read",
    "blog.grid.posts.5.source": "Johns Hopkins Medicine",
    "blog.grid.posts.6.title": "How to Master Visualization Techniques to Overcome Game-Time Nerves",
    "blog.grid.posts.6.excerpt": "USA Track & Field explores how visualization — the practice of carefully rehearsing a situation in your mind until it feels familiar — helps athletes feel composed when high-pressure moments arrive in competition.",
    "blog.grid.posts.6.category": "Mental Skills",
    "blog.grid.posts.6.readTime": "5 min read",
    "blog.grid.posts.6.source": "USA Track & Field",
    "blog.grid.posts.7.title": "Importance of Sports Psychology: A Meta-Analysis of 127 Studies",
    "blog.grid.posts.7.excerpt": "A meta-analysis encompassing over 24,000 participants confirms that mental skills training measurably improves athletic performance. The findings link anxiety management to consistency, confidence, and long-term athlete development.",
    "blog.grid.posts.7.category": "Research",
    "blog.grid.posts.7.readTime": "10 min read",
    "blog.grid.posts.7.source": "SportsPhychology.org",
    "blog.grid.posts.8.title": "How Athletes Can Build Grit for Sports",
    "blog.grid.posts.8.excerpt": "Exploring practical strategies for developing perseverance and passion in athletic contexts — from deliberate practice to growth mindset cultivation. Based on Duckworth's framework applied to youth and competitive sport settings.",
    "blog.grid.posts.8.category": "Mental Skills",
    "blog.grid.posts.8.readTime": "7 min read",
    "blog.grid.posts.8.source": "Exact Sports",
    "blog.newsletter.titleA": "Stay in the",
    "blog.newsletter.titleB": "Loop",
    "blog.newsletter.subtitle": "Get curated mental performance resources delivered to your inbox — the latest research, practical guides, and expert insights for athletes, parents, and coaches.",
    "blog.newsletter.placeholder": "Your email address",
    "blog.newsletter.button": "Subscribe",
    "blog.newsletter.note": "No spam. Unsubscribe anytime.",
    # --- FAQ page ---
    "faq.hero.eyebrow": "FAQ",
    "faq.hero.titleA": "Questions?",
    "faq.hero.titleB": "We've Got Answers.",
    "faq.hero.subtitle": "Everything you need to know about the Athletic Mindset assessment, reports, pricing, and how to get started for athletes, parents, and coaches.",
    "faq.cta.titleA": "Still Have",
    "faq.cta.titleB": "Questions?",
    "faq.cta.subtitle": "Our team is here to help. Reach out and we'll get back to you within one business day.",
    "faq.cta.contact": "Contact Us",
    "faq.cta.assessment": "Take Free Assessment",
    "faq.sections.0.title": "About the Assessment",
    "faq.sections.0.items.0.question": "What exactly does the Athletic Mindset assessment measure?",
    "faq.sections.0.items.0.answer": "The assessment measures 22 dimensions of mental performance organized into 8 factors across 3 phases: Preparation (Work Style, Coachability, Grit), Competition (Drive, Focus, Mental Toughness), and Teamwork (Leadership Potential, Team Orientation). Every athlete receives a Total Athletic Mindset Score plus granular scores for each dimension.",
    "faq.sections.0.items.1.question": "How long does the assessment take?",
    "faq.sections.0.items.1.answer": "About 15 to 20 minutes for a complete evaluation. Athletes answer questions covering all 22 dimensions. There are no wrong answers, it's a self-evaluation of mental tendencies and preferences.",
    "faq.sections.0.items.2.question": "Is the assessment scientifically validated?",
    "faq.sections.0.items.2.answer": "Yes. The assessment is built on peer-reviewed sport psychology and organizational psychology research, validated against 5,000+ athletes across 60+ sports. All dimension scales meet professional psychometric reliability standards. It was developed by Dr. Brian Marentette, Ph.D. in Industrial/Organizational Psychology.",
    "faq.sections.0.items.3.question": "How is my score calculated?",
    "faq.sections.0.items.3.answer": "Your raw responses are converted to T-scores (mean 50, standard deviation 10) using our norming population of 5,000+ athletes. Scores range from 20 to 80, where 50 is exactly average. You also receive percentile rankings both overall and within your specific sport and competition level.",
    "faq.sections.0.items.4.question": "Can I retake the assessment?",
    "faq.sections.0.items.4.answer": "Yes, unlimited reassessments are included with the Elite Report. The platform tracks your progress over time and highlights your biggest improvements.",
    "faq.sections.0.items.5.question": "What sports does it cover?",
    "faq.sections.0.items.5.answer": "The assessment covers 60+ sports. Mental performance dimensions like confidence, focus, and composure are universal across sports, but your scores are benchmarked against athletes in your specific sport and competition level for the most relevant comparison.",
    "faq.sections.1.title": "Reports & Results",
    "faq.sections.1.items.0.question": "What's included in the free tier?",
    "faq.sections.1.items.0.answer": "The free tier includes the full 22-dimension assessment, 1 factor score unlocked (of 8), your overall Athletic Mindset score, and basic percentile ranking. It's a real taste of the platform, enough to see where you stand and decide if you want the full depth.",
    "faq.sections.1.items.1.question": "What does the Elite Report add?",
    "faq.sections.1.items.1.answer": "The Elite Report unlocks everything: full detailed report across all 22 dimensions, personalized Gameplan with specific mental skills, sport-specific benchmarking, elite athlete comparison (D1/Pro level), all 7 Situational Mindset profiles, unlimited reassessments, and progress tracking over time.",
    "faq.sections.1.items.2.question": "Do parents and coaches take a separate assessment?",
    "faq.sections.1.items.2.answer": "No, only athletes take the assessment. Parents and coaches each receive their own tailored report generated from the athlete's results. The Parent Report focuses on communication and support guidance. The Coach Report focuses on development strategy and how to coach each athlete effectively.",
    "faq.sections.1.items.3.question": "What are the six mental skills in my Gameplan?",
    "faq.sections.1.items.3.answer": "Based on your scores, your Gameplan recommends from six evidence-based mental skills: Self-Talk (controlling your inner narrative), Arousal Control (managing energy and anxiety), Visualization (mental rehearsal), Routines (consistent preparation), Goal Setting (directing focus), and Re-Framing (turning setbacks into fuel).",
    "faq.sections.2.title": "For Parents",
    "faq.sections.2.items.0.question": "What does the Parent Report include?",
    "faq.sections.2.items.0.answer": "The Parent Report translates your child's assessment data into plain, jargon-free language. It includes their overall mental profile, a Coachability spotlight (how your child receives feedback), their motivation profile (intrinsic vs. extrinsic), specific communication guidance, conversation starters tied to their scores, and when to seek additional mental performance support.",
    "faq.sections.2.items.1.question": "Can I see my child's detailed scores?",
    "faq.sections.2.items.1.answer": "The Parent Report shows your child's factor-level scores with context and interpretation, but framed around how you can support them, not raw numbers without guidance. The goal is actionable understanding, not data overload.",
    "faq.sections.2.items.2.question": "How much does it cost for a parent?",
    "faq.sections.2.items.2.answer": "The Athlete + Parent Elite bundle is $15/month or $175/year. This includes the full athlete report AND a dedicated Parent Gameplan report at no extra cost. The free tier is always available to try first.",
    "faq.sections.3.title": "For Coaches",
    "faq.sections.3.items.0.question": "How does the coach dashboard work?",
    "faq.sections.3.items.0.answer": "Once athletes on your team complete assessments, you see their mental readiness at a glance, factor scores, development areas, leadership potential, and role recommendations. The Coach Report for each athlete includes specific guidance on how to communicate with and develop that player.",
    "faq.sections.3.items.1.question": "What is the Partner Revenue Share program?",
    "faq.sections.3.items.1.answer": "Coaches can earn 30% of every athlete subscription that comes through their referral link, paid monthly via Stripe. Share your unique link or QR code with your athletes, and earn passive income while helping them develop their mental game. One club director with 90 athletes could earn $1,600+/year.",
    "faq.sections.3.items.2.question": "Can I use this for my entire team?",
    "faq.sections.3.items.2.answer": "Yes. We offer team and club packages for programs with 20+ athletes. Bulk onboarding, roster-wide analytics, and dedicated support are included. Contact us for custom pricing based on your program size.",
    "faq.sections.4.title": "Pricing & Billing",
    "faq.sections.4.items.0.question": "Is there really a free tier?",
    "faq.sections.4.items.0.answer": "Yes, completely free, no credit card required. Take the full 22-dimension assessment, get your overall score and 1 unlocked factor. It's not a trial, it's a permanent free tier you can use anytime.",
    "faq.sections.4.items.1.question": "What's the difference between monthly and yearly pricing?",
    "faq.sections.4.items.1.answer": "Yearly billing saves you money compared to paying month-by-month. Both include all features with no restrictions.",
    "faq.sections.4.items.2.question": "Can I cancel anytime?",
    "faq.sections.4.items.2.answer": "Yes, cancel with one tap, no questions asked. If you're on a monthly plan, you'll retain access through the end of your billing period. No hidden fees, no long-term commitments.",
    # --- Club & School page ---
    "club.hero.pre": "The best athletic programs don't just manage programs. They build culture. And culture transforms lives.",
    "club.hero.titleA": "Transform Your",
    "club.hero.titleB": "Program's Mentality.",
    "club.hero.subtitle": "Athletic Mindset gives your program a complete mental performance system, every athlete assessed, every coach equipped, every team stronger.",
    "club.hero.cta": "Talk to Our Team",
    "club.hero.ctaSecondary": "Explore the System",
    "club.hero.scroll": "Built for high schools, clubs, colleges, and entire school systems.",
    "club.who.eyebrow": "Who It's For",
    "club.who.titleA": "Built for Programs of",
    "club.who.titleB": "Every Size",
    "club.who.subtitle": "Whether you run a single club team or an entire district's athletics, Athletic Mindset gives you the deepest level of understanding of your athletes and your teams.",
    "club.who.audiences.0": "High School Programs",
    "club.who.audiences.1": "Club & Travel Teams",
    "club.who.audiences.2": "Colleges & Universities",
    "club.who.audiences.3": "Professional Teams",
    "club.who.audiences.4": "Entire School Systems",
    "club.who.audiences.5": "Camps & Academies",
    "club.measures.eyebrow": "Team Measures",
    "club.measures.titleA": "Go Beyond the",
    "club.measures.titleB": "Sum of Individuals",
    "club.measures.subtitle": "The Team Mindset assessment reveals what makes your teams tick, cohesion, culture, collective confidence, and the dynamics that decide whether a group of athletes becomes a real team.",
    "club.measures.groups.0.label": "Team Process",
    "club.measures.groups.0.title": "How your teams work together",
    "club.measures.groups.0.points.0": "Preparation, how teams plan, strategize, and align on goals",
    "club.measures.groups.0.points.1": "Competition, how athletes coordinate and execute in the moment",
    "club.measures.groups.0.points.2": "Interpersonal, the trust and harmony that hold a team together",
    "club.measures.groups.1.label": "Teamwork Culture",
    "club.measures.groups.1.title": "The identity that shapes behavior",
    "club.measures.groups.1.points.0": "Values, the principles your team truly identifies with",
    "club.measures.groups.1.points.1": "Expectations, the unspoken standards for how things get done",
    "club.measures.groups.1.points.2": "Consistency between coach strategy and team culture",
    "club.measures.groups.2.label": "Team Strength",
    "club.measures.groups.2.title": "What drives results on the field",
    "club.measures.groups.2.points.0": "Leadership strength across your designated leaders",
    "club.measures.groups.2.points.1": "Team cohesion, collective confidence, and shared commitment",
    "club.measures.groups.2.points.2": "Role clarity, everyone knowing and owning their part",
    "club.get.eyebrow": "A System for the Whole Program",
    "club.get.titleA": "One Platform,",
    "club.get.titleB": "Every Team",
    "club.get.subtitle": "Athletic Mindset scales from a single team to an entire school system, with the tools to assess, equip, and track everyone.",
    "club.get.features.assessed.title": "Every Athlete Assessed",
    "club.get.features.assessed.desc": "A complete 22-dimension mental profile and personalized gameplan for every athlete across your program.",
    "club.get.features.equipped.title": "Every Coach Equipped",
    "club.get.features.equipped.desc": "Coach and summary reports for every team, so your staff can develop the mental game, not just the physical one.",
    "club.get.features.programView.title": "Program-Wide View",
    "club.get.features.programView.desc": "See mental readiness across every team from one place, spot patterns, gaps, and standout leaders program-wide.",
    "club.get.features.bulk.title": "Bulk Onboarding",
    "club.get.features.bulk.desc": "Invite entire rosters at once with a simple import. Get your whole program set up in minutes, not weeks.",
    "club.get.features.unlimited.title": "Unlimited Teams",
    "club.get.features.unlimited.desc": "One system for every squad, level, and season, from your youngest club team to your varsity roster.",
    "club.get.features.culture.title": "A Culture That Lasts",
    "club.get.features.culture.desc": "Build shared language and mental standards across teams, so culture carries from one season to the next.",
    "club.cta.titleA": "Build a Program That",
    "club.cta.titleB": "Wins the Mental Game",
    "club.cta.subtitle": "Let's design the right rollout for your program. Reach out and we'll put together a plan and pricing that fits your size and goals.",
    "club.cta.button": "Talk to Our Team",
    # --- Partner Program page ---
    "partners.hero.badge": "Revenue Share Partner Program",
    "partners.hero.titleA": "Earn While You",
    "partners.hero.titleB": "Coach.",
    "partners.hero.subtitle": "Coaches and club directors who partner with Athletic Mindset earn recurring revenue by sharing a platform their athletes already need. No selling. No upfront cost. Just share a link.",
    "partners.hero.cta": "Join the Partner Program",
    "partners.hero.note": "No approval required · Free to join · Earn from day one",
    "partners.hero.stats.revShare": "Rev Share",
    "partners.hero.stats.upfront": "Upfront Cost",
    "partners.hero.stats.payoutsValue": "Monthly",
    "partners.hero.stats.payouts": "Payouts",
    "partners.hero.stats.recurringValue": "Forever",
    "partners.hero.stats.recurring": "Recurring",
    "partners.how.eyebrow": "How It Works",
    "partners.how.titleA": "From Zero to",
    "partners.how.titleB": "Earning in 3 Minutes",
    "partners.how.subtitle": "No sales pitch. No long onboarding. Sign up, share your link, and start earning when your athletes subscribe.",
    "partners.how.steps.0.title": "Sign Up Free",
    "partners.how.steps.0.desc": "Create your partner account in 60 seconds. No approval required. No credit card. No upfront cost.",
    "partners.how.steps.1.title": "Get Your Link & QR",
    "partners.how.steps.1.desc": "Receive your unique referral link and downloadable QR code instantly. Share it any way you want.",
    "partners.how.steps.2.title": "Share With Your Athletes",
    "partners.how.steps.2.desc": "Text it to your team, post it at practice, or hand out printed QR codes at tournaments. One link does it all.",
    "partners.how.steps.3.title": "Earn Every Month",
    "partners.how.steps.3.desc": "Earn 30 to 40% of every athlete subscription, automatically deposited via Stripe.",
    "partners.tiers.eyebrow": "Partner Tiers",
    "partners.tiers.titleA": "Grow Your Roster.",
    "partners.tiers.titleB": "Grow Your Rate.",
    "partners.tiers.subtitle": "Your revenue share increases automatically as more of your athletes subscribe. No action needed, tier upgrades happen on their own.",
    "partners.tiers.mostPopular": "Most Popular",
    "partners.tiers.revShare": "rev share",
    "partners.tiers.perAthlete": "/athlete/month",
    "partners.tiers.getStarted": "Get Started",
    "partners.tiers.note": "Tournament partners & governing bodies qualify for custom institutional agreements.",
    "partners.tiers.contactUs": "Contact us",
    "partners.tiers.tiers.starter.name": "Starter",
    "partners.tiers.tiers.starter.requirement": "1-14 paid athletes",
    "partners.tiers.tiers.starter.features.0": "Partner dashboard access",
    "partners.tiers.tiers.starter.features.1": "Unique referral link & QR code",
    "partners.tiers.tiers.starter.features.2": "Pre-written sharing templates",
    "partners.tiers.tiers.starter.features.3": "Monthly Stripe payouts",
    "partners.tiers.tiers.starter.features.4": "Real-time earnings tracking",
    "partners.tiers.tiers.growth.name": "Growth",
    "partners.tiers.tiers.growth.requirement": "15-49 paid athletes",
    "partners.tiers.tiers.growth.features.0": "Everything in Starter, plus:",
    "partners.tiers.tiers.growth.features.1": "Priority partner support",
    "partners.tiers.tiers.growth.features.2": "Coach-to-coach referral bonuses",
    "partners.tiers.tiers.growth.features.3": "Upgrade nudge tools for free athletes",
    "partners.tiers.tiers.growth.features.4": "Monthly earnings summary emails",
    "partners.tiers.tiers.elite.name": "Elite",
    "partners.tiers.tiers.elite.requirement": "50+ paid athletes",
    "partners.tiers.tiers.elite.features.0": "Everything in Growth, plus:",
    "partners.tiers.tiers.elite.features.1": "Featured in partner directory",
    "partners.tiers.tiers.elite.features.2": "Quarterly strategy calls",
    "partners.tiers.tiers.elite.features.3": "Co-marketing opportunities",
    "partners.tiers.tiers.elite.features.4": "Early access to new features",
    "partners.tiers.tiers.elite.features.5": "Ambassador badge & recognition",
    "partners.earnings.eyebrow": "The Math",
    "partners.earnings.titleA": "Real Coaches.",
    "partners.earnings.titleB": "Real Earnings.",
    "partners.earnings.subtitle": "You earn up to 40% of every athlete subscription linked to your referral code. Every month. Forever.",
    "partners.earnings.recurring": "recurring",
    "partners.earnings.note": "Based on $9.99/month athlete subscription. Earnings scale automatically as your roster grows, no cap on how much you can earn.",
    "partners.earnings.examples.0.type": "Youth Travel Coach",
    "partners.earnings.examples.0.athletes": "20 athletes",
    "partners.earnings.examples.0.rate": "40% convert",
    "partners.earnings.examples.1.type": "Club Director (1 team)",
    "partners.earnings.examples.1.athletes": "30 athletes",
    "partners.earnings.examples.1.rate": "50% convert",
    "partners.earnings.examples.2.type": "Club Director (3 teams)",
    "partners.earnings.examples.2.athletes": "90 athletes",
    "partners.earnings.examples.2.rate": "50% convert",
    "partners.earnings.examples.3.type": "Large Club Owner",
    "partners.earnings.examples.3.athletes": "200 athletes",
    "partners.earnings.examples.3.rate": "50% convert",
    "partners.dashboard.eyebrow": "Your Partner Dashboard",
    "partners.dashboard.titleA": "Built to Make Earning",
    "partners.dashboard.titleB": "Visible & Effortless",
    "partners.dashboard.subtitle": "Every time you open your dashboard, you see money. That's by design. When earnings are visible, partners share more.",
    "partners.dashboard.mock.thisMonth": "This month",
    "partners.dashboard.mock.change": "↑ 23% vs last month",
    "partners.dashboard.mock.subscribers": "From 38 active subscribers",
    "partners.dashboard.mock.tier": "Growth Tier · 35% rate",
    "partners.dashboard.mock.payout": "Next payout: Jul 15",
    "partners.dashboard.features.earnings.title": "Earnings Dashboard",
    "partners.dashboard.features.earnings.desc": "Your monthly earnings front and center, large, prominent, and motivating. See exactly what your athletes generate for you.",
    "partners.dashboard.features.roster.title": "Athlete Roster",
    "partners.dashboard.features.roster.desc": "Track every athlete linked to your code. See who's subscribed, who's free, and who's ready for an upgrade nudge.",
    "partners.dashboard.features.history.title": "Earnings History",
    "partners.dashboard.features.history.desc": "Month-by-month earnings chart with projections. Watch your revenue compound as your roster grows.",
    "partners.dashboard.features.tools.title": "Share & Grow Tools",
    "partners.dashboard.features.tools.desc": "One-tap link sharing, downloadable QR codes, pre-written text and email templates. Make sharing effortless.",
    "partners.dashboard.features.payouts.title": "Automated Payouts",
    "partners.dashboard.features.payouts.desc": "Stripe Connect handles everything. Monthly deposits on the 15th, 1099 tax docs, full transaction history.",
    "partners.dashboard.features.leaderboard.title": "Leaderboard & Badges",
    "partners.dashboard.features.leaderboard.desc": "See how you rank among other partners. Earn shareable badges as you grow. Coaches are competitive, use it.",
    "partners.tournament.eyebrow": "Tournament & Institutional Partners",
    "partners.tournament.titleA": "One Tournament.",
    "partners.tournament.titleB": "Hundreds of Partners.",
    "partners.tournament.para1": "Tournaments create awareness at scale. When 500 teams hear about Athletic Mindset in one weekend, coaches sign up, athletes subscribe, and the flywheel spins itself.",
    "partners.tournament.para2": "Institutional partners, tournaments, governing bodies, leagues, earn a 5% override on all revenue generated by coaches they refer. No cap. No sponsorship fees. Pure performance.",
    "partners.tournament.stats.0.label": "Regional Tournament",
    "partners.tournament.stats.0.teams": "50 teams",
    "partners.tournament.stats.0.athletes": "750 athletes",
    "partners.tournament.stats.0.revenue": "$1,839/month approx.",
    "partners.tournament.stats.1.label": "National Tournament",
    "partners.tournament.stats.1.teams": "500 teams",
    "partners.tournament.stats.1.athletes": "7,500 athletes",
    "partners.tournament.stats.1.revenue": "$18,357/month approx.",
    "partners.tournament.flywheelLabel": "The Flywheel",
    "partners.tournament.flywheelText": "One tournament partnership, hundreds of coaches, thousands of athletes, years of recurring revenue.",
    "partners.cta.titleA": "Stop Coaching for Free.",
    "partners.cta.titleB": "Start Earning.",
    "partners.cta.subtitle": "Your athletes need mental performance training. You get paid to give them access. Everyone wins.",
    "partners.cta.button": "Join the Partner Program",
    "partners.cta.secondary": "Talk to Us First",
    "partners.cta.stat1": "No approval needed",
    "partners.cta.stat2": "Earn 30-40% forever",
    "partners.cta.stat3": "Monthly payouts via Stripe",
}


async def _seed_missing(db) -> int:
    """Insert only English keys that don't exist yet; never overwrite edits."""
    master = settings.CONTENT_MASTER_LOCALE
    result = await db.execute(
        select(ContentEntry.key).where(ContentEntry.locale == master)
    )
    existing = {row[0] for row in result.all()}

    added = 0
    for key, value in CONTENT.items():
        if key not in existing:
            db.add(ContentEntry(key=key, locale=master, value=value))
            added += 1
    if added:
        await db.commit()
    return added


async def ensure_seeded() -> None:
    """Auto-seed missing content. Safe to run on every startup and deploy."""
    async with AsyncSessionLocal() as db:
        added = await _seed_missing(db)
    if added:
        print(f"✓ seeded {added} new content string(s)")


async def main() -> None:
    await ensure_seeded()
    print("Done. New languages fill in on first view; existing edits untouched.")


if __name__ == "__main__":
    asyncio.run(main())
